### ISSUE TITLE
google library issue

### ISSUE THREAD

**Issue by yamunajakku** [upasana05ghosh/Question-Answering-System#1]
I had installed google library still it is showing as no module found for google
google is very much essential for this project as the answer will be searched in google only
please help me with this as soon as possible
thank u

reference text:

C:\Users\User\Desktop\Yamuna\QAS>pip2 install google --user
Requirement already satisfied: google in c:\python27\lib\site-packages (2.0.1)
Requirement already satisfied: beautifulsoup4 in c:\python27\lib\site-packages (from google) (4.6.3)

C:\Users\User\Desktop\Yamuna\QAS>python app.py
Traceback (most recent call last):
  File "app.py", line 24, in <module>
    from give_answer import answer_question
  File "C:\Users\User\AppData\Roaming\Python\Python27\site-packages\gevent\builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "C:\Users\User\Desktop\Yamuna\QAS\give_answer.py", line 4, in <module>
    from google import google
  File "C:\Users\User\AppData\Roaming\Python\Python27\site-packages\gevent\builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named google

**Comment by ankitcsr** [comment]
install this library 
pip install git+https://github.com/abenassi/Google-Search-API

**Comment by upasana05ghosh** [comment]
Try : https://stackoverflow.com/questions/36183486/importerror-no-module-named-google
